services:
  worker1:
    build:
      context: ../..
      dockerfile: workres/worker1/Dockerfile
    container_name: worker1
    env_file:
      - ../../.env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      TASKS_QUEUE: tasks:double
      WORKER_NAME: worker1
      OPERATION_NAME: double
    depends_on:
      - redis
    restart: unless-stopped
