services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: api
    env_file:
      - ../.env
    volumes:
      - ./:/app/api
      - ../.env:/app/.env
    ports:
      - "${APP_PORT:-8000}:80"
    depends_on:
      - redis
    restart: unless-stopped
